-- PatoLex Gate D — Initial schema migration
-- Generated by drizzle-kit, then hand-edited.
--
-- ============================================================
-- HAND-EDITED SECTIONS (search "HAND-EDITED"):
--
--   1. btree_gist extension  (before all DDL)
--      Drizzle cannot emit CREATE EXTENSION statements.
--      Required for the GiST exclusion constraints on provision_version
--      and designation_history.
--
--   2. uuid_generate_v7() function  (before the provision table)
--      PostgreSQL has no built-in UUIDv7 generator. This function encodes
--      the millisecond unix timestamp in bits 0-47, sets version nibble (7)
--      and variant bits, and fills the remainder with random bits.
--      Referenced by the provision.public_id column default.
--      Drizzle cannot emit function definitions.
--
--   3. provision_version GiST exclusion constraint
--      Drizzle pg-core cannot express EXCLUDE USING gist constraints.
--      Guarantees no two provision_version rows for the same provision_id
--      have overlapping valid_range values.
--
--   4. designation_history GiST exclusion constraint
--      Same no-overlap guarantee for designation labels.
--
--   5. CHECK constraint on source_document.ocr_cer_estimate
--      Enforces 0 <= value <= 1 when non-null.
--
--   6. DEFERRABLE INITIALLY DEFERRED on self-referential FKs in change_event
--      Applies to supersedes_id, superseded_by_id, double_jointed_with_id.
--      Removes the bidirectional-delete trap; rows that reference each other
--      can be inserted/deleted within a single transaction.
--      Drizzle does not support DEFERRABLE on FK definitions.
--
-- NOT hand-edited (Drizzle-native after adversarial-review revision):
--   - provision_version.fts_vector GENERATED ALWAYS AS ... STORED  (line ~77)
--   - idx_provision_version_fts USING gin  (line ~118)
--   - provision.public_id DEFAULT uuid_generate_v7()  (line ~64)
-- ============================================================

-- HAND-EDITED (1): btree_gist extension required for GiST exclusion constraints.
CREATE EXTENSION IF NOT EXISTS btree_gist;--> statement-breakpoint

-- HAND-EDITED (2): UUIDv7 generator function.
-- Encodes the current millisecond unix timestamp into bits 0-47 of the UUID,
-- sets the version nibble to 7 (bits 76-79) and the variant bits (bits 64-65),
-- and fills the remaining bits with cryptographic randomness.
-- This produces time-ordered, globally unique identifiers suitable for B-tree
-- index locality during bulk ingest.
CREATE OR REPLACE FUNCTION uuid_generate_v7()
RETURNS uuid
LANGUAGE plpgsql
AS $$
DECLARE
  unix_ms bigint;
  hex     text;
BEGIN
  -- Current time in milliseconds since Unix epoch (48 bits).
  unix_ms := (extract(epoch FROM clock_timestamp()) * 1000)::bigint;
  -- Encode: 12 hex digits of timestamp + version nibble '7' + 3 hex random
  --         + variant nibble (8|9|a|b) + 12 hex random.
  -- Layout: tttttttttttt-7xxx-Vxxxxxxxxxxx  (where V is the variant nibble)
  hex :=
    lpad(to_hex(unix_ms), 12, '0') ||             -- 48-bit timestamp (12 hex)
    '7' || lpad(to_hex((random() * 4095)::int), 3, '0') ||  -- version 7 + 12 random bits
    to_hex(8 + (random() * 3)::int) ||            -- variant: 1000|1001|1010|1011 (hex 8-b)
    lpad(to_hex((random() * 1099511627775)::bigint), 11, '0') || -- 44 random bits
    lpad(to_hex((random() * 281474976710655)::bigint), 12, '0'); -- 48 random bits
  RETURN (
    substr(hex, 1, 8)  || '-' ||
    substr(hex, 9, 4)  || '-' ||
    substr(hex, 13, 4) || '-' ||
    substr(hex, 17, 4) || '-' ||
    substr(hex, 21, 12)
  )::uuid;
END;
$$;--> statement-breakpoint

CREATE TYPE "public"."change_action" AS ENUM('enact', 'amend', 'repeal', 'add', 'renumber', 'recodify', 'reserve');--> statement-breakpoint
CREATE TYPE "public"."enactment_kind" AS ENUM('statute', 'recodification', 'regulatory_action');--> statement-breakpoint
CREATE TYPE "public"."lineage_edge_type" AS ENUM('renumber', 'transfer', 'split', 'merge', 'repeal_reenact', 'repeal_without_successor');--> statement-breakpoint
CREATE TYPE "public"."provision_status" AS ENUM('active', 'repealed', 'reserved', 'superseded');--> statement-breakpoint
CREATE TYPE "public"."source_type" AS ENUM('session_law', 'bill', 'annotated_edition', 'scan', 'regulatory_action', 'official_xml');--> statement-breakpoint
CREATE TYPE "public"."trust_level" AS ENUM('official_xml', 'human_verified', 'derived', 'ocr_uncertain');--> statement-breakpoint
CREATE TYPE "public"."unit_type" AS ENUM('code_section', 'act_section', 'reg_section');--> statement-breakpoint
CREATE TABLE "change_event" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "change_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"enactment_id" bigint NOT NULL,
	"provision_id" bigint NOT NULL,
	"action" "change_action" NOT NULL,
	"new_text" text,
	"operative_date" date,
	"in_act_order" integer NOT NULL,
	"supersedes_id" bigint,
	"superseded_by_id" bigint,
	"double_jointed_with_id" bigint,
	"chaptered_out" boolean DEFAULT false NOT NULL,
	"diff_from_prior" jsonb,
	"source_document_id" bigint,
	"page_ref" text,
	"trust_level" "trust_level" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "designation_history" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "designation_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"provision_id" bigint NOT NULL,
	"code" text,
	"section_number" text NOT NULL,
	"label" text,
	"valid_range" daterange NOT NULL
);
--> statement-breakpoint
CREATE TABLE "enactment" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "enactment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"source_document_id" bigint,
	"citation" text,
	"jurisdiction" text NOT NULL,
	"session" text,
	"legislature" text,
	"chapter_number" integer,
	"chaptered_date" date,
	"effective_date" date,
	"operative_date" date,
	"title" text,
	"bill_number" text,
	"kind" "enactment_kind" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "lineage_edge" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "lineage_edge_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"enactment_id" bigint NOT NULL,
	"predecessor_provision_id" bigint NOT NULL,
	"successor_provision_id" bigint,
	"edge_type" "lineage_edge_type" NOT NULL,
	"text_disposition" text,
	"continues" boolean,
	"note" text
);
--> statement-breakpoint
CREATE TABLE "provision" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "provision_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT uuid_generate_v7() NOT NULL,
	"jurisdiction" text NOT NULL,
	"unit_type" "unit_type" NOT NULL,
	"current_designation" text,
	"status" "provision_status" DEFAULT 'active' NOT NULL,
	CONSTRAINT "provision_public_id_unique" UNIQUE("public_id")
);
--> statement-breakpoint
CREATE TABLE "provision_version" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "provision_version_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"provision_id" bigint NOT NULL,
	"text" text,
	"valid_range" daterange NOT NULL,
	"fts_vector" "tsvector" GENERATED ALWAYS AS (to_tsvector('english', coalesce("text", ''))) STORED,
	"trust_level" "trust_level" NOT NULL,
	"source_change_event_id" bigint,
	"source_document_id" bigint
);
--> statement-breakpoint
CREATE TABLE "source_document" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "source_document_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"type" "source_type" NOT NULL,
	"citation" text,
	"jurisdiction" text NOT NULL,
	"source_channel" text,
	"scan_quality" text,
	"ocr_engine" text,
	"ocr_cer_estimate" double precision,
	"trust_level" "trust_level" NOT NULL,
	"retrieved_at" timestamp with time zone,
	"clean_channel" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
ALTER TABLE "change_event" ADD CONSTRAINT "change_event_enactment_id_enactment_id_fk" FOREIGN KEY ("enactment_id") REFERENCES "public"."enactment"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "change_event" ADD CONSTRAINT "change_event_provision_id_provision_id_fk" FOREIGN KEY ("provision_id") REFERENCES "public"."provision"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "change_event" ADD CONSTRAINT "change_event_supersedes_id_change_event_id_fk" FOREIGN KEY ("supersedes_id") REFERENCES "public"."change_event"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "change_event" ADD CONSTRAINT "change_event_superseded_by_id_change_event_id_fk" FOREIGN KEY ("superseded_by_id") REFERENCES "public"."change_event"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "change_event" ADD CONSTRAINT "change_event_double_jointed_with_id_change_event_id_fk" FOREIGN KEY ("double_jointed_with_id") REFERENCES "public"."change_event"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "change_event" ADD CONSTRAINT "change_event_source_document_id_source_document_id_fk" FOREIGN KEY ("source_document_id") REFERENCES "public"."source_document"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "designation_history" ADD CONSTRAINT "designation_history_provision_id_provision_id_fk" FOREIGN KEY ("provision_id") REFERENCES "public"."provision"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "enactment" ADD CONSTRAINT "enactment_source_document_id_source_document_id_fk" FOREIGN KEY ("source_document_id") REFERENCES "public"."source_document"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lineage_edge" ADD CONSTRAINT "lineage_edge_enactment_id_enactment_id_fk" FOREIGN KEY ("enactment_id") REFERENCES "public"."enactment"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lineage_edge" ADD CONSTRAINT "lineage_edge_predecessor_provision_id_provision_id_fk" FOREIGN KEY ("predecessor_provision_id") REFERENCES "public"."provision"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lineage_edge" ADD CONSTRAINT "lineage_edge_successor_provision_id_provision_id_fk" FOREIGN KEY ("successor_provision_id") REFERENCES "public"."provision"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "provision_version" ADD CONSTRAINT "provision_version_provision_id_provision_id_fk" FOREIGN KEY ("provision_id") REFERENCES "public"."provision"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "provision_version" ADD CONSTRAINT "provision_version_source_change_event_id_change_event_id_fk" FOREIGN KEY ("source_change_event_id") REFERENCES "public"."change_event"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "provision_version" ADD CONSTRAINT "provision_version_source_document_id_source_document_id_fk" FOREIGN KEY ("source_document_id") REFERENCES "public"."source_document"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_change_event_provision_date" ON "change_event" USING btree ("provision_id","operative_date");--> statement-breakpoint
CREATE INDEX "idx_change_event_enactment_id" ON "change_event" USING btree ("enactment_id");--> statement-breakpoint
CREATE INDEX "idx_designation_history_provision_id" ON "designation_history" USING btree ("provision_id");--> statement-breakpoint
CREATE INDEX "idx_lineage_edge_predecessor" ON "lineage_edge" USING btree ("predecessor_provision_id");--> statement-breakpoint
CREATE INDEX "idx_lineage_edge_successor" ON "lineage_edge" USING btree ("successor_provision_id");--> statement-breakpoint
CREATE INDEX "idx_lineage_edge_enactment_id" ON "lineage_edge" USING btree ("enactment_id");--> statement-breakpoint
CREATE INDEX "idx_provision_version_provision_id" ON "provision_version" USING btree ("provision_id");--> statement-breakpoint
CREATE INDEX "idx_provision_version_fts" ON "provision_version" USING gin ("fts_vector");--> statement-breakpoint

-- HAND-EDITED (3): GiST exclusion constraint on provision_version.
-- Drizzle pg-core cannot express EXCLUDE USING gist constraints.
-- Guarantees no two provision_version rows for the same provision_id may have
-- overlapping valid_range values — exactly one result for any (provision_id, date)
-- point-in-time query:
--   SELECT text FROM provision_version
--   WHERE provision_id = $1 AND valid_range @> $2::date
-- Requires btree_gist (added at top).
ALTER TABLE "provision_version"
  ADD CONSTRAINT "provision_version_provision_id_valid_range_excl"
  EXCLUDE USING gist (provision_id WITH =, valid_range WITH &&);--> statement-breakpoint

-- HAND-EDITED (4): GiST exclusion constraint on designation_history.
-- Same no-overlap guarantee for designation labels. A (provision_id, date) pair
-- matches at most one designation_history row — the ORDER BY ... LIMIT 1 pattern
-- is no longer needed; a plain equality query is sufficient.
--   SELECT section_number FROM designation_history
--   WHERE provision_id = ? AND valid_range @> D::date
-- Requires btree_gist (added at top).
ALTER TABLE "designation_history"
  ADD CONSTRAINT "designation_history_provision_id_valid_range_excl"
  EXCLUDE USING gist (provision_id WITH =, valid_range WITH &&);--> statement-breakpoint

-- HAND-EDITED (5): CHECK constraint on source_document.ocr_cer_estimate.
-- Enforces that the OCR character error rate is in [0, 1] when non-null.
ALTER TABLE "source_document"
  ADD CONSTRAINT "source_document_ocr_cer_estimate_check"
  CHECK (ocr_cer_estimate IS NULL OR (ocr_cer_estimate >= 0 AND ocr_cer_estimate <= 1));--> statement-breakpoint

-- HAND-EDITED (6): DEFERRABLE INITIALLY DEFERRED on self-referential FKs.
-- The three self-referential FKs on change_event reference each other
-- bidirectionally (supersedes_id ↔ superseded_by_id; double_jointed_with_id
-- points at a peer row). Making them DEFERRABLE INITIALLY DEFERRED removes the
-- bidirectional-insert/delete ordering trap: within a single transaction, all FK
-- checks are deferred until COMMIT, so you can insert or delete a pair of rows
-- in any order. The table is append-only in normal operation, but deferred FKs
-- simplify ETL and bulk-load scripts.
-- Drizzle does not support DEFERRABLE on FK definitions.
ALTER TABLE "change_event"
  ALTER CONSTRAINT "change_event_supersedes_id_change_event_id_fk"
  DEFERRABLE INITIALLY DEFERRED;--> statement-breakpoint
ALTER TABLE "change_event"
  ALTER CONSTRAINT "change_event_superseded_by_id_change_event_id_fk"
  DEFERRABLE INITIALLY DEFERRED;--> statement-breakpoint
ALTER TABLE "change_event"
  ALTER CONSTRAINT "change_event_double_jointed_with_id_change_event_id_fk"
  DEFERRABLE INITIALLY DEFERRED;
