# comms-watcher.ps1 -- Monitors Claude Code <-> Codex CLI comms files
#
# PURPOSE:
#   Watches docs/00_Inbox/comms/to-codex.md and from-codex.md for changes.
#   When either file is modified, reads the new content and appends it
#   (with datetime stamp and sender tag) to the transcript file.
#
# USAGE:
#   powershell -ExecutionPolicy Bypass -File .claude\scripts\comms-watcher.ps1
#
#   Runs until terminated (Ctrl+C or close terminal).
#   Start at the beginning of a session, leave running.
#
# OUTPUT:
#   docs/00_Inbox/comms/transcript.md -- append-only, full conversation history

param(
    [string]$RepoRoot = (Split-Path -Parent (Split-Path -Parent $PSScriptRoot))
)

$commsDir = Join-Path $RepoRoot "docs\00_Inbox\comms"
$transcriptFile = Join-Path $commsDir "transcript.md"
$toCodexFile = Join-Path $commsDir "to-codex.md"
$fromCodexFile = Join-Path $commsDir "from-codex.md"

# Initialize transcript if it doesn't exist
if (-not (Test-Path $transcriptFile)) {
    $header = "# Claude Code <-> Codex CLI Conversation Transcript`n`n"
    $header += "**Auto-generated by comms-watcher.ps1** -- do not edit manually.`n`n"
    $header += "---`n"
    Set-Content -Path $transcriptFile -Value $header -Encoding UTF8
}

$lastToCodex = ""
$lastFromCodex = ""

Write-Host "[comms-watcher] Watching: $commsDir"
Write-Host "[comms-watcher] Transcript: $transcriptFile"
Write-Host "[comms-watcher] Press Ctrl+C to stop."

$watcher = New-Object System.IO.FileSystemWatcher
$watcher.Path = $commsDir
$watcher.Filter = "*.md"
$watcher.NotifyFilter = [System.IO.NotifyFilters]::LastWrite
$watcher.EnableRaisingEvents = $false

while ($true) {
    $watcher.WaitForChanged([System.IO.WatcherChangeTypes]::Changed, 2000) | Out-Null

    if (Test-Path $toCodexFile) {
        $content = Get-Content -Path $toCodexFile -Raw -ErrorAction SilentlyContinue
        if ($content -and $content -ne $lastToCodex) {
            $lastToCodex = $content
            $timestamp = Get-Date -Format "2026-05-31 HH:mm:ss"
            $entry = "`n`n## [$timestamp] CLAUDE CODE -> CODEX`n`n$content"
            Add-Content -Path $transcriptFile -Value $entry -Encoding UTF8
            Write-Host "[$timestamp] Logged: CC -> Codex message"
        }
    }

    if (Test-Path $fromCodexFile) {
        $content = Get-Content -Path $fromCodexFile -Raw -ErrorAction SilentlyContinue
        if ($content -and $content -ne $lastFromCodex) {
            $lastFromCodex = $content
            $timestamp = Get-Date -Format "2026-05-31 HH:mm:ss"
            $entry = "`n`n## [$timestamp] CODEX -> CLAUDE CODE`n`n$content"
            Add-Content -Path $transcriptFile -Value $entry -Encoding UTF8
            Write-Host "[$timestamp] Logged: Codex -> CC message"
        }
    }
}
